# opt-in to Travis new container-based infrastructure
sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk: openjdk8
language: scala
scala: 2.12.12

install:
  - sbt update

script:
  - sbt compile
  - sbt test
